sudo: false
dist: trusty
language: rust
cache: cargo

install:
- rustup component add rustfmt clippy
- rustup target add wasm32-unknown-unknown

script:
- cargo build
- cargo test --all-features
- cargo clippy -- -Dwarnings
- cargo clippy --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --no-deps
